version: '3.9'

services:

  encoder:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: .env
    deploy:
      mode: replicated
      replicas: 1

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
